image: docker:stable

services:
  - docker:dind

stages:
  - spawn
  - build

variables:
  CONTAINER_IMAGE: git.sitesoft.ru:4567/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2

.ci_scripts: &ci_scripts |
  apk add --no-cache curl
  export NOW_TIMESTAMP=$(date +'%Y%m%d%H%M%S')
  docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.sitesoft.ru:4567

  function trigger_build() {
    local project_id="$1";            # Project ID (integer)
    local trigger_token="$2";         # Trigger token (string)
    local branch_name="${3:-master}"; # Branch name (string)

    URL="http://git.sitesoft.ru/api/v4/projects/$project_id/trigger/pipeline";

    curl -L \
      --request POST \
      --form "token=$trigger_token" \
      --form "ref=$branch_name" \
      "$URL";
  }

spawn_containers:
  stage: spawn
  script:
    - echo "Start docker-containers for compile sources"
    - *ci_scripts

build and push image:
  stage: build
  only:
    - master
  script:
    - docker build --tag $CONTAINER_IMAGE:$NOW_TIMESTAMP --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$NOW_TIMESTAMP
    - docker push $CONTAINER_IMAGE:latest

test image building:
  stage: build
  except:
    - master
  script:
    - docker build --cache-from $CONTAINER_IMAGE:latest .
