version: '2'

services:
  example-data:
    container_name: example-data
    build:
      context: example-data-container
      dockerfile: Dockerfile
    volumes:
      - /example-data

  nginx:
    container_name: nginx
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NGINX_HTTP_CONFIGS: '/example-data/nginx-configs/no-ssl.conf /example-data/nginx-configs/ssl.conf'
      WWW_DATA_ACCESSIBLE_DIRS: '/example-data/www'
      NGINX_RESOLVERS: '1.1.1.1 1.0.0.1'
    volumes_from:
      - example-data
    ports:
     - "8080:80"
     - "1443:443"
